In [2]:
import pandas as pd

train = pd.read_csv('data/train_all_features.csv')

In [3]:
train.describe()

,CUST_COD,LIMIT_BAL,SEX,PAY_DEC,PAY_NOV,PAY_OCT,PAY_SEP,PAY_AUG,PAY_JUL,BILL_AMT_DEC,...,BILL_AMT_SIGMA,PAY_AMT_AR,PAY_AMT_I,PAY_AMT_MA,PAY_AMT_SIGMA,PAY_AR,PAY_I,PAY_MA,PAY_SIGMA,TOTAL_AMT_PAID
count,2.688400e+04,26884.00000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,...,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000,26884.000000
mean,3.506806e+07,4997.91411,0.607387,-0.016367,-0.133313,-0.166344,-0.219052,-0.264879,-0.291884,1530.136656,...,274.229883,0.066062,0.123828,0.001860,156.647793,0.008816,0.130003,0.000074,0.399668,950.194554
std,1.423976e+07,3879.73624,0.488341,1.123991,1.197715,1.197837,1.171221,1.135089,1.150547,2206.111841,...,490.883185,0.304260,0.335878,0.043941,406.917235,0.096994,0.336424,0.008625,0.452654,1842.985628
min,1.015513e+07,298.13600,0.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-4936.535888,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.275616e+07,1490.68000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,105.115300,...,29.523440,0.000000,0.000000,0.000000,15.018421,0.000000,0.000000,0.000000,0.000000,199.803294
50%,3.519585e+07,4173.90400,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,667.198554,...,98.783014,0.000000,0.000000,0.000000,36.244106,0.000000,0.000000,0.000000,0.372678,430.582918
75%,4.727209e+07,7155.26400,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1997.891324,...,316.522424,0.000000,0.000000,0.000000,110.256831,0.000000,0.000000,0.000000,0.745356,1001.908388
max,5.963161e+07,29813.60000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,28755.545150,...,17630.179344,2.000000,2.000000,2.000000,17693.056062,2.000000,2.000000,1.000000,2.683282,112220.358100